export const DATA_FETCHED = 'DATA_FETCHED';
export const DATA_SUCCEEDED = 'DATA_SUCCEEDED';
export const DATA_FAILED = 'DATA_FAILED';

export const EDITOR_TEXT_CHANGED = 'TEXT_CHANGED';
export const EDITOR_MOVE_CURSOR  = 'MOVE_CURSOR';
