export const EDITOR_TEXT_CHANGED = 'TEXT_CHANGED';
export const EDITOR_TEXT_ADDED = 'TEXT_ADDED';
export const EDITOR_MOVE_CURSOR  = 'MOVE_CURSOR';

export const EDITOR_UPDATE_CHAR_SIZE = 'UPDATE_CHAR_SIZE';
export const EDITOR_INVALIDATE_CHAR_SIZE  = 'INVALIDATE_CHAR_SIZE';
