export const EDITOR_LINE_CHANGED      = 'LINE_CHANGED';
export const EDITOR_NEW_LINE          = 'EDITOR_NEW_LINE';
export const EDITOR_MOVE_UP_CURSOR    = 'MOVE_UP_CURSOR';
export const EDITOR_MOVE_DOWN_CURSOR  = 'MOVE_DOWN_CURSOR';
export const EDITOR_MOVE_LEFT_CURSOR  = 'MOVE_LEFT_CURSOR';
export const EDITOR_MOVE_RIGHT_CURSOR = 'MOVE_RIGHT_CURSOR';
export const EDITOR_BACKSPACE         = 'BACKSPACE';
