export const DATA_FETCHED = 'DATA_FETCHED';
export const DATA_SUCCEEDED = 'DATA_SUCCEEDED';
export const DATA_FAILED = 'DATA_FAILED';

export const EDITOR_TEXT_CHANGED = 'TEXT_CHANGED';
export const EDITOR_MOVE_CURSOR  = 'MOVE_CURSOR';

export const EDITOR_UPDATE_CHAR_SIZE = 'UPDATE_CHAR_SIZE';
export const EDITOR_INVALIDATE_CHAR_SIZE  = 'INVALIDATE_CHAR_SIZE';
